apiVersion: apps/v1
kind: Deployment
metadata:
  name: marxcat
  labels:
    app: marxcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marxcat
  template:
    metadata:
      labels:
        app: marxcat
    spec:
      containers:
        - name: web
          image: registry.gitlab.com/sztern.kevin/marxcat:498e2ab9
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: marxcat
spec:
  selector:
    app: marxcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marxcat
spec:
  ingressClassName: nginx
  rules:
  - host: marxcat.loutre.tel
    http:
      paths:
      - backend:
          service:
            name: marxcat
            port:
              name: http
        path: /
        pathType: Prefix
