{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "logs-secret",
    "namespace": "grafana",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "logs-secret",
        "namespace": "grafana",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "password": "AgCO1MqsZZf/ivoTnaAZbjEzfEk1BQkLddFtYWMk6YqXAGQXRD1biekFPXVRDdY7p0JZnntrMCltD74r1QZ9vyAyha6oL7PQdwolXnZm4lj6AINF0JLyd7jHhT2CLTqhFvDRlblTdU1LpDJsxAiCKr8s/t/TQBznqgClsly5q6IrhCpe0TCro5brFEiXe2ER5LGsjTUmyK+mEE12GillDcgkx5Vb56WcmQHqD3yMimbDCsN81CEaeDtzuwdNR+pcio1JI8qYEA+qu7smJkt+PMAzpnhIUDzXv+VvRA+h4NtgbScgrQQdn8sN1PD+GArL4GM0un9chsIeGTI1hYOYhbHwfwglejgeLEYH3dpqLzYZmNlAQcNG/S0rAcSZ0VLNdNXfy4jxBq+fTDZ2yg1gsCk11T7kTb/ycXxwLWzGLirAHs6avMUJMohsqv5txG2ec3829pqo6eUgUujtMSSN5ph/byJqA/pjJi2gOpLqpMpfjF+O6ad6M6WAf9esdTaAIF1Y81/E0AVcgpcba2yg/YTJOoiO2kdMh4MDhSMouIrQ4kfeiGlG2g9MqwB/oXpd3isp99tKgZRiXumc5vOnDjpucKo4skrFlOV4G29GmuU270SThhcCYbA02oOWGjNaHLgkB10rVifpIup2YMp0IrqwrI0IKtU8Eqark2Epx132TsEj2V4KRTB/QqcKcAvXBIi0RRA88IqkTK9weD0cjITCk7GmEg2wQRZEJucUwKUF5pah7uWjXIHtnRR337fLnn2wbIiRLgHAL9ip6Cael1UOTVFGmAM+GyX5vzDvy8Eg4NDwNFYcxoa7LMra1K+ctpkqPx0u66myR9ykMiiKJ0ypife7r1CqToQr0rNOHBvHCk3zj4i7GTj3iPTIJA==",
      "username": "AgCuyYxWlcCMtavzyLhBxoIFaISaA3b7FKe8TdyYlPMOf6LC7zg+g2fjamJoMStkaRy8ZKybQxa65vo163uRz2t6PGq6GVulO+qzJHcTTv+mjdzlNeLQp3nYiCo6mfrf5lSbim5SaADg8gX6BRUIT6wofSPqs2XC7bCBoc3FjH9dAN4FbD1CnhI5QEHJ70HoHzS02AZWmAcdG5FoJFF3jYYUVkanHP78Y+MbEk4JTgTx8CARP1Qfr0qz+t/DmiKN1s77byAA2CPU4dRywjtEMirhKHN1WWSOhHpeWkMGV7PC9tB1XK8s6a2rIRs0j8VsyLAvWF25bP53U/FoV9PIkGHS2lkv3abZVxXSVgxcAQQ81OFiAGUO/zXbuohNud2UANcbkxRtoecXCmb8Twp+HkANMuKrAoBn3JbOk6WtEv2yVnig5S8lJ1xvW3yQAYoxj9db2ZUn0a5ysWRINF20dBf96TMuIyMjYHfUXW3iAAXZ0KNl4GnHzl7N5PvJ/JytHg0/vhtHG+qo0PkgIVKaDPgVGGhh282551eky7AACFEz37voWm6NItKySH9OB5t/E5ybT9XZ9+/LfEUXlt5Pa3bJMnJSUsbTZpbc06HjB5TAVmR//cZqCy2wRlX4YLbe8CSVRlrwznxMc9DI4E/dMPjhTTM2WOewYcEENW+s84j1BYA71F3swdWcG8Phk1gWCtJoESqxv1w="
    }
  }
}
