apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  labels:
    agent: grafana-agent
  name: grafana-agent-metrics
  namespace: monitoring
spec:
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  remoteWrite:
  - url: http://mimir-nginx/api/v1/push
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: cadvisor-monitor
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 60s
    metricRelabelings:
    - action: keep
      regex: container_network_receive_packets_total|kube_daemonset_status_number_available|kubelet_server_expiration_renew_errors|go_goroutines|kube_horizontalpodautoscaler_spec_max_replicas|kubelet_running_pods|kubelet_running_pod_count|kube_pod_status_reason|kube_deployment_status_observed_generation|kubelet_pleg_relist_duration_seconds_count|kubelet_pleg_relist_interval_seconds_bucket|kubelet_pod_start_duration_seconds_bucket|container_fs_reads_total|namespace_cpu:kube_pod_container_resource_requests:sum|kube_statefulset_status_observed_generation|kube_node_spec_taint|storage_operation_duration_seconds_count|kubelet_node_name|kube_daemonset_status_updated_number_scheduled|kube_statefulset_status_replicas|kubelet_pod_worker_duration_seconds_count|node_namespace_pod_container:container_memory_working_set_bytes|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kubelet_certificate_manager_client_ttl_seconds|kubelet_volume_stats_capacity_bytes|node_filesystem_avail_bytes|node_filesystem_size_bytes|kube_job_status_active|kubernetes_build_info|container_network_transmit_packets_total|kubelet_cgroup_manager_duration_seconds_bucket|kube_job_failed|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|kubelet_pleg_relist_duration_seconds_bucket|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|volume_manager_total_volumes|process_resident_memory_bytes|kube_node_status_capacity|kube_job_status_start_time|container_network_transmit_bytes_total|kubelet_pod_worker_duration_seconds_bucket|kube_pod_owner|namespace_memory:kube_pod_container_resource_limits:sum|kube_statefulset_replicas|kubelet_certificate_manager_server_ttl_seconds|kubelet_running_container_count|kube_deployment_status_replicas_available|kubelet_runtime_operations_errors_total|kube_horizontalpodautoscaler_status_desired_replicas|kubelet_volume_stats_available_bytes|kube_pod_container_resource_limits|namespace_workload_pod|kube_statefulset_status_replicas_ready|kube_replicaset_owner|container_memory_working_set_bytes|container_memory_cache|kubelet_certificate_manager_client_expiration_renew_errors|namespace_workload_pod:kube_pod_owner:relabel|node_namespace_pod_container:container_memory_rss|kubelet_runtime_operations_total|container_cpu_cfs_periods_total|kube_deployment_status_replicas_updated|kube_namespace_status_phase|kubelet_node_config_error|kube_pod_info|kube_daemonset_status_number_misscheduled|container_fs_reads_bytes_total|kube_horizontalpodautoscaler_status_current_replicas|storage_operation_errors_total|kube_node_info|kube_pod_container_resource_requests|kube_pod_status_phase|kube_node_status_allocatable|kube_pod_container_status_waiting_reason|container_cpu_cfs_throttled_periods_total|node_namespace_pod_container:container_memory_swap|kubelet_cgroup_manager_duration_seconds_count|kubelet_volume_stats_inodes_used|kube_deployment_metadata_generation|container_fs_writes_bytes_total|kube_statefulset_status_update_revision|kube_statefulset_metadata_generation|kube_statefulset_status_replicas_updated|kube_node_status_condition|container_cpu_usage_seconds_total|process_cpu_seconds_total|kube_daemonset_status_desired_number_scheduled|kube_statefulset_status_current_revision|kubelet_running_containers|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|kubelet_volume_stats_inodes|container_fs_writes_total|namespace_cpu:kube_pod_container_resource_limits:sum|node_namespace_pod_container:container_memory_cache|kube_daemonset_status_current_number_scheduled|container_network_receive_bytes_total|rest_client_requests_total|machine_memory_bytes|container_memory_rss|namespace_memory:kube_pod_container_resource_requests:sum|kube_resourcequota|kube_deployment_spec_replicas|container_network_receive_packets_dropped_total|container_network_transmit_packets_dropped_total|container_memory_swap|kube_horizontalpodautoscaler_spec_min_replicas|kubelet_pod_start_duration_seconds_count|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|kube_persistentvolumeclaim_resource_requests_storage_bytes|kube_namespace_status_phase|container_cpu_usage_seconds_total|kube_pod_status_phase|kube_pod_start_time|kube_pod_container_status_restarts_total|kube_pod_container_info|kube_pod_container_status_waiting_reason|kube_daemonset.*|kube_replicaset.*|kube_statefulset.*|kube_job.*|kube_node.*|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|namespace_cpu:kube_pod_container_resource_requests:sum|node_cpu.*|node_memory.*|node_filesystem.*
      sourceLabels:
      - __name__
    path: /metrics/cadvisor
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    - action: replace
      replacement: integrations/kubernetes/cadvisor
      targetLabel: job
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: ksm-monitor
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 60s
    path: /metrics
    port: http-metrics
    relabelings:
    - action: replace
      replacement: integrations/kubernetes/kube-state-metrics
      targetLabel: job
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: kubelet-monitor
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 60s
    path: /metrics
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    - action: replace
      replacement: integrations/kubernetes/kubelet
      targetLabel: job
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
---
