apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent
  name: agent-eventhandler
  namespace: monitoring
spec:
  config:
    cache_path: /etc/eventhandler/eventhandler.cache
    logs_instance: monitoring/grafana-agent-logs
  name: eventhandler
  type:
    unique: true
  volumeMounts:
  - mountPath: /etc/eventhandler
    name: agent-eventhandler
  volumes:
  - name: agent-eventhandler
    persistentVolumeClaim:
      claimName: agent-eventhandler
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent
  name: node-exporter
  namespace: monitoring
spec:
  config:
    autoscrape:
      enable: true
      metrics_instance: monitoring/grafana-agent-metrics
    procfs_path: host/proc
    rootfs_path: /host/root
    sysfs_path: /host/sys
    relabel_configs:
    - action: replace
      replacement: node-exporter
      targetLabel: job
  name: node_exporter
  type:
    allNodes: true
    unique: true
  volumeMounts:
  - mountPath: /host/root
    name: rootfs
  - mountPath: /host/sys
    name: sysfs
  - mountPath: /host/proc
    name: procfs
  volumes:
  - hostPath:
      path: /
    name: rootfs
  - hostPath:
      path: /sys
    name: sysfs
  - hostPath:
      path: /proc
    name: procfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-eventhandler
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
