apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  labels:
    agent: grafana-agent
  name: grafana-agent-logs
  namespace: monitoring
spec:
  clients:
    - url: http://loki-gateway/loki/api/v1/push
  podLogsNamespaceSelector: {}
  podLogsSelector:
    matchLabels:
      instance: primary
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  labels:
    instance: primary
  name: kubernetes-logs
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  pipelineStages:
  - cri: {}
  selector:
    matchLabels: {}
---
