namespace: monitoring
helmCharts:
  - name: grafana
    version: 6.55.0
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    valuesInline:
      grafana.ini:
        server:
          domain: grafana.loutre.tel
      ingress:
        enabled: true
        hosts: ["grafana.loutre.tel"]
        ingressClassName: nginx
      persistence:
        enabled: true
      admin:
        existingSecret: grafana
        userKey: admin-user
        passwordKey: admin-password
  - name: loki
    version: 5.2.0
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: monitoring
    valuesInline:
      loki:
        commonConfig:
          replication_factor: 1
        storage:
          type: 'filesystem'
        auth_enabled: false
      singleBinary:
        replicas: 1
        persistence:
          enableStatefulSetAutoDeletePVC: false
      gateway:
        affinity: ""
      monitoring:
        selfMonitoring:
          enabled: false
          grafanaAgent:
            installOperator: false
      test:
        enabled: false
  - name: grafana-agent-operator
    version: 0.2.15
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana-agent-operator
    namespace: monitoring
    includeCRDs: true
  - name: kube-state-metrics
    version: 5.6.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-state-metrics
    namespace: monitoring
    valuesInline:
      prometheusScrape: false
      prometheus:
        monitor:
          enabled: true
      selfMonitor:
        enabled: true


resources:
  - sealed-secret-grafana.yaml
  - grafana-agent.yaml
  - grafana-agent-logs.yaml
