namespace: monitoring
helmCharts:
  - name: grafana
    version: 6.56.1
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    valuesFile: grafana-values.yaml

  - name: loki
    version: 5.3.1
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: monitoring
    valuesFile: loki-values.yaml

  - name: mimir-distributed
    version: 4.3.1
    repo: https://grafana.github.io/helm-charts
    releaseName: mimir
    namespace: monitoring
    valuesFile: mimir-values.yaml

  - name: grafana-agent
    version: 0.13.0
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana-agent
    namespace: monitoring
    includeCRDs: true
    valuesFile: grafana-agent-values.yaml

  - name: kube-state-metrics
    version: 5.6.1
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-state-metrics
    namespace: monitoring
    valuesInline:
      prometheusScrape: false
      selfMonitor:
        enabled: true


resources:
  - sealed-secret-grafana.yaml

configMapGenerator:
  - name: grafana-agent
    files:
      - config.river
    options:
      disableNameSuffixHash: true

# TODO: Remove this when update 0.34 hits
patchesJSON6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: grafana-agent
    patch: |-
      - op: add
        path: /rules/0/resources/-
        value: nodes/metrics
