namespace: monitoring
helmCharts:
  - name: grafana
    version: 6.52.9
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    valuesInline:
      grafana.ini:
        server:
          domain: grafana.loutre.tel
      ingress:
        enabled: true
        hosts: ["grafana.loutre.tel"]
        ingressClassName: nginx
      persistence:
        enabled: true
  - name: loki
    version: 5.1.0
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: monitoring
    valuesInline:
      loki:
        commonConfig:
          replication_factor: 1
        storage:
          type: 'filesystem'
      singleBinary:
        replicas: 1
