apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCz5ynV2+KvNefS47e4MwfHCymwBJ44ZMjlDOnD3XYVKE8Qh+S55b5AEz4K79L2s/GTlcTtvp7cTTPEsHWctzrEesTWT7oJYrOHKQzb0zEZddtFDIwgv3HqnPDV8uU+UffRWqEyeL9oWzSHyOQZiMHKsacrVloqMmBL8I5CWEac5NxKcMdgMjAR9hQtZ5ZeCyRcHTyXR4zNBYtshHB3nNR+aTN1GWhUxS6ug2kFruCPXeBW1LUZw9bJgTzj+mqXO2ypVgH4cW/U8h0dKJRfSE3Fx7fJqJHSYNQC173pYQ+pxUKWAbp8LeMM+3Nunv1neCtu7SIF7USYH+w3yMkRhohnLqfgXRezBsC6WpMXZf95gcffE24Fnlmly9tmDKXmtDGlV5FAwLQ116ly0uuXaHVeX9h0ylJGPFtvYTxNsze+7UDX91rTSv4JewvG/drJR0oa31RTuDuzSYHzLP8xXTIbXHecjuxXtpWU7nueuQceY8xl+/6dlINWuDJ4Lw/eDBOQ6pCAJivPLqSHPU6bPFEWejKtN5Ltj1aqfRcwQsVTAJAyoA6tvGvVwFMeFOqFYe6r8E5uiA9HMYqy4unUCIRg/aowtUWsVf0LESyrvzNi9k9+zVngeUD+WCMTKelpKI+HIxoz+j0PSyoAp1haGQgUStUHUrqwnGKt8BcSaXvsm7rMh4uPaCY1nRME/rgQ/bPAp7GiK818VLSy1u16+EKrkGFDnAs3FH6i8oDOP1UtJ800Pw1zMMb1
    admin-user: AgB05kjj88yXum04WtJpqVXqPWAAWraIi49/FOqlrfhFvEPY8qG9VGJxidUnkMFkfKV7YEqyObTL85b+EEraINHLFAoLyQqBwLbtY5ZZs3wtZw3zhPQ65KBSbPE7pVZInNwDmrgxJoA71fvVPHqiXA4OhlvC50pCyW8jkr3EXh1OYn9+O3dRvrbwWj5gmqZ/PZANbsItSRgRF0MnGD1fnrl3n6ZByjgPyDpDdZ/krnulOo4e3ITZKHYsrkDsB5dPC7k8kkr3uAAiEEjDJZYKRH2DVXGW/dD4u7yyqzp3QaKeIXbEWFn3Tb4ywhOgaFotefKZEwPmLIU0WRxeAG8ZkK3X/zomM4hiCoKPl3yV2EzA9//NpsRqXPSowNbr9iR7Io6LqxVgBMWMcAD40v0XHmZGIUlTnX0xxKvwH9lBCGnxqhq1Ivyvjy8fG2H+Oij8aC7siFB6tBSetoTjtLr1YPe+MoYinm381rPeVA4Gt8D0hY2AiHqFtKyGkQd2FXAJoGsALEimCxpMUa1QmEntwjcETaoRRPr9pwzxQi6k4zW0RX3U+NoAvkrSK9+e7k58KHwqUxac30d51OFjoKAeQ2Ar3CyUKtTZTd282OdpKB57UHJ01OC4lUbV64D2uwl1nn1s1wrB3zyAW95GrctFhryJIa2ZfjDYyQjypobNL3+cuprD25QpWrg28FOO/d+3DQ7dbOSj3A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

