namespace: openebs
helmCharts:
  - name: openebs
    version: 3.10.0
    repo: https://openebs.github.io/charts
    releaseName: openebs
    namespace: openebs
    includeCRDs: true
    valuesInline:
      lvm-localpv:
        enabled: true

resources:
  - storage-class-lvm.yaml
