apiVersion: apps/v1
kind: Deployment
metadata:
  name: ack-s3-controller
  namespace: ack-system
spec:
  template:
    spec:
      containers:
        - name: controller
          volumeMounts:
          - name: aws-creds
            mountPath: "/root/.aws/credentials"
            readOnly: true
      volumes:
        - name: aws-creds
          secret:
            secretName: aws-creds
