apiVersion: apps/v1
kind: Deployment
metadata:
  name: ack-s3-controller
  namespace: ack-system
spec:
  template:
    spec:
      containers:
        - name: controller
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/credentials/credentials-file"
          volumeMounts:
          - name: aws-creds
            mountPath: "/credentials"
            readOnly: true
      volumes:
        - name: aws-creds
          secret:
            secretName: aws-creds
