apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA5UFwtqgK9w88Bhw0hEIRMfu5KlnDLqLDaGZG5g34I6J3Yq1nwPnRjjR7hEJ01i1/Wuo5pPFBCo1Dty7MERfhTQXpZ2SWqGbUQ89uBqZIzMUauadndLu0QSGKJaSnvQ6CBsNO8FYeshTveK8S3vYH00xT5/zYB2ZxJbWIlBdvDLjzjMdIsmBdbBUM2a0u1J+noOqGYPRx8fIt1VQnF0MOjx+EC/8d09a8pfPZWbhj2eV22Z6QxPSCaGyPAM/XTdP7pTu4+HUKDoguUv8nff0xZPSawRvOmg7ZH7fczPZpVSzJLcc43XBHa95Ge4Xj1bmalpZpiiKlqG55zNiJUOm7ZxiUJ6yBT21oKsC31arzgyRxWzhPG1bLG9ubSAQxasgr+irXhnSk/1tOAc2OqisvNJcKKfQA1L19yxB/N+Vmg9/0MW0EGVKaQG8otS1rhU5d4erTz9ZTRuwOTiS5nt5pmb1EPXWQ6AvOSDVp8vHh/2R1vzZtrEa/CGy/2IK1zeezIocSR4ZwWLJ+/58/7FDO8ZR0Z9puhGVvvFvjI2SC5YOjTvl8uguaZiWzJ+odrw6pzCKN6zo9wXvf754h3M8C2HE1+HcKu+mUxmwZ4BxzE5FfWMsTqTlQFzSCQx5p/H1JhiT1S5v5WVQzfGv2yo6VEPwZnditm2FH8qaq85jc4eYxkO58/iAE44GflfNgQff4lh21E/jH5dpRPkluNKN29cXhbhfsUkqq9+zuOiCehw9kaZ87BHZChyDaw7B/vIXQoyIFvTUlX0QeplTd+cxVjS0HtRPQxQRF/04nAaVh7xQ6WRiX3edCkjfN84+n5ZxEH7c+K2Pf0qci3szrc1Gb4vKgil34=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        component: velero
      name: cloud-credentials
      namespace: velero
    type: Opaque

