apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp: null
  name: daily
  namespace: velero
spec:
  schedule: '@every 24h'
  template:
    csiSnapshotTimeout: 0s
    hooks:
      resources:
        - name: mariadb
          labelSelector:
            matchLabels:
              app: mariadb
          pre:
            - exec:
              command:
                - /bin/sh
                - -c
                - mariadb --password=$MYSQL_PASSWORD -e "BACKUP STAGE START; BACKUP STAGE BLOCK_COMMIT"
          pre:
            - exec:
              command:
                - /bin/sh
                - -c
                - mariadb --password=$MYSQL_PASSWORD -e "BACKUP STAGE END"
    includedNamespaces:
    - '*'
    metadata: {}
    ttl: 720h0m0s
  useOwnerReferencesInBackup: false
