grafana:
  grafana.ini:
    server:
      domain: grafana.loutre.tel
  ingress:
    enabled: true
    hosts: ["grafana.loutre.tel"]
    ingressClassName: nginx
  persistence:
    enabled: true

loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  singleBinary:
    replicas: 1
