apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loutretel-tsig-secret
  namespace: cert-manager
spec:
  encryptedData:
    tsig-secret-key: AgBNYMOP2FmeqEPdzG0dsm7G/NzgRcJZdvBuipWmKc8lj2zmL46leQ2ETFnmrIJbw+bX584atCJLzGMaHS7UcEo9CBUdb6TEaL79tjLGOqHuRS0m7PwGWEm3JzBQjhbslLX/dpneU+nugqIsI0wP6Bc7vVqPH9tF2ZtKJ1genYw2dojTZr5SOB1H9/BNjEt61U6sjDQ9yy2Tm9IP1OB+AOVx34Loy/GfrZCN/P9gpy2qe1U6Mc5PF8zflmqWY4YnRtQsaq5q45Ix+y55HkmKIkN9IkdAQQ6XF1RjySmvR0i8YzSCncGuuzxeKIN9b9IB4fXhjv7/ljg2wK/vlqmAYcxIwPUkELS1piWF3RNLjreYlc9/yOxsqFz5CGS0Hd3NeN5mcFkkHnXu/UrReSxqpXoslZR4jszmjko4SY3zVbwAqYY64UgNrPHMvXMbsT2PitG+hYNOqyN5EZ8ev3YLkbihwzLdqjufnX0SHNvq6roZBaw95LPRXFUcyEjmZebygyHDxwHI3ieXWxy/zZB2JuuK0/oTnKa3t87tZYDSs3b0uMXjnvvD8rm23w2YcKyInJE/S1xA2JoJLbi0C4GGT50cPzEW0mkXfaFm3S78AzSRkxD+lWnwXfEBuDuV8EoBN4gqRb4ABL7j/Uyea847X7wZXAbP89gfCaQcK+EH8VdMA9Ec/e7KXBm0G77aqOQzWRSBkjf69xj54PbmoEXt2UaiLAQfgyvnDZT1l47cO/y1NRO4dJqlnxh7LDY6AS4RK3tRbmbbaxWxNkG4yziwTNv1UViBaaUSEqx1pYnnND6iDmsvLFZSX/Bhtg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: loutretel-tsig-secret
      namespace: cert-manager

