apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: cert-manager
spec:
  dnsNames:
  - loutre.tel
  - "*.loutre.tel"
  - kevinsztern.fr
  - "*.kevinsztern.fr"
  - mesburnes.fr
  - "*.mesburnes.fr"
  - deliciousmuffins.net
  - "*.deliciousmuffins.net"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: wildcard-tls
  privateKey:
    rotationPolicy: Always
