namespace: ingress-nginx
helmCharts:
  - name: ingress-nginx
    version: 4.6.0
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesInline:
      controller:
        config:
          force-ssl-redirect: "true"
        extraArgs:
          default-ssl-certificate: cert-manager/wildcard-tls
