namespace: kube-system
helmCharts:
  - name: cilium
    version: 1.16.3
    repo: https://helm.cilium.io
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    valuesInline:
      kubeProxyReplacement: strict
      k8sServiceHost: 148.251.135.212
      k8sServicePort: 64443
      operator:
        replicas: 1
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
        tls:
          auto:
            method: cronJob
      certgen:
        ttlSecondsAfterFinished: ''
